spring.application.name=food-ordering-backend

# Server
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/food_ordering_db

# Application settings
spring.jackson.time-zone=Asia/Kolkata
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.springframework.data.mapping=DEBUG